include:
- ./func/*
kind: ArchiveUploadSpec
name: func-Ja91

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-w8-ben-fn-f7f58726-b2eb-4809-9e3d-a03de70709d1
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-w8-ben-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-Ja91
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-08T16:54:12Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-w8-ben-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-w8-ben-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_w8_ben
    packageref:
      name: get-w8-ben-fn-f7f58726-b2eb-4809-9e3d-a03de70709d1
      namespace: default
  requestsPerPod: 1
  resources: {}
