apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-w8-ben-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-w8-ben-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding/get_w8_ben
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /onboarding/get_w8_ben
